apiVersion: v1
kind: Pod
metadata:
  name: wrong-interface-app
  labels:
    app: wrong-interface-app
spec:
  containers:
  - name: wrong-interface-app
    image: wrong-interface-app:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wrong-interface-service
spec:
  selector:
    app: wrong-interface-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
